security:
    password_hashers:
        App\Entity\User:
            algorithm: auto


    providers:
        nucleos_user:
            id: nucleos_user.user_provider.username_email
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            stateless: false
            provider: nucleos_user
            form_login:
                login_path: /login
                check_path: /login_check
                username_parameter: username
                password_parameter: password
                default_target_path: /dashboard 
                failure_path: /   # Optional: Redirect to login page on failure
                failure_forward: true
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
