security:
    password_hashers:
        App\Entity\User:
            algorithm: auto


    providers:
        nucleos_user:
            id: nucleos_user.user_provider.username_email
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: false
            provider: nucleos_user
            form_login:
                login_path: startingPoint
                check_path: /login_check
                username_parameter: username
                password_parameter: password
                default_target_path: /dashboard 
                failure_path: /   # Optional: Redirect to login page on failure
                failure_forward: true
            logout:
                path: /logout
                target: /

    access_control:

        
        - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/employess, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/users, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/equipment, roles: IS_AUTHENTICATED_FULLY } 
    access_denied_url: startingPoint